### ISSUE TITLE
V210 KiCAD Project?

### ISSUE THREAD

**Issue by ajayre** [laszlodaniel/ChryslerCCDSCIScanner#13]
Hi, Would you would be willing to add the KiCAD project to github? I am interested in this project for my 2006 Jeep Wrangler. I could create my own KiCAD project from the schematic but it would save me a lot of time to just use yours. Thanks! Andy

**Comment by laszlodaniel** [comment]
Hi, no way. Good luck with your project!

**Comment by ajayre** [comment]
OK, no problem. I appreciate you making this all open source. The DRB III Emulator I have does not work with the PCI bus even with the "XX TI MAP" ground pin fix, so this is pretty interesting to me. I have the emulator running in a virtual machine so maybe the issue is there. I've forked your project. For future reference are you interested in pull requests or do you prefer to work alone on this project?

**Comment by laszlodaniel** [comment]
VirtualBox pulled the same behavior on me. The USB comm was not properly routed between host OS (Win 10) and guest OS (Win 7). In the host OS a single Linux USB driver needs to be auto-installed and nothing else. And make sure to follow Emulator installation instructions in the guest OS to the T. I'll get back to you with my setup on Monday.

There are other nuances you should be aware of, while using the Micropod and Emulator. It needs to talk to the PCM on SCI-bus first, to identify the controller, then it moves on to PCI-bus. So if you work on the bench this can make things difficult.
For me the Emulator failed frequently when I bench-tested PCI-bus with a SKIM unit.

For now I want to work on this repository alone, since it's very old and much of the code needs to be cleaned up. Suggestions and protocols are welcome! Although I use the Micropod to extract diagnostic procedures, ever so slowly.

**Comment by ajayre** [comment]
I can access the PCM (presumably via SCI) and I can scan for modules and it finds them, but even though the scan finds the MIC for example I cannot access it. And because all of this is a black box there are no debugging options. Your solution looks much better.
