### ISSUE TITLE
Bootstrap/Programming

### ISSUE THREAD

**Issue by ajayre** [laszlodaniel/ChryslerCCDSCIScanner#14]
Am I right in understanding that the bootstrap/programming only relates to the SBEC and not JTEC, JTEC+ or NGC?
Thanks, Andy

**Comment by laszlodaniel** [comment]
No, the method of bootstrapping applied here is valid for all of those and EATX3 as well. They are all wired to sense high voltages (12V/20V) on their SCI-RX pin. Programming was tested on SBEC/EATX/JTEC units. Protocol for NGC is different and not tested yet.

**Comment by ajayre** [comment]
Cool - thanks for letting me know. For some reason my abilities with Google to find this information are letting me down. Do you know of a source for technical documents to that level for the NGC or are you working all of this out by reverse engineering the DRB III?

**Comment by laszlodaniel** [comment]
No public documentation is available since I got into this game. It's reverse engineering all the way!
You will find this NGC reflashing log most interesting: [05143318AA_DCX2534.txt](https://github.com/laszlodaniel/ChryslerScanner/files/11891755/05143318AA_DCX2534.txt)
Same protocol applies to NGC1-3 (PCI/SCI-bus).
Please open a new [Discussion](https://github.com/laszlodaniel/ChryslerScanner/discussions) if you have further questions!
